### ISSUE TITLE
How to update the style of markdown code highlight?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#10]
I want to change markdown code highlight to GitHub style, but I don't know how to make it.

Thanks,

Sincerely,
Robin

**Comment by yulijia** [comment]
Please see Part 3 ,  at the bottom of [this article](http://yulijia.net/freshman21/articles/howto/2014/12/19/freshman21-structure.html)

**Comment by dbarobin** [comment]
I updated the code formatting section of  `_base.scss`, then the style of markdown code highlight changed. I don't run this repo locally, so I won't install pygments, just update the `_syntax-highlighting.scss` file, is it  true?

**Comment by yulijia** [comment]
<code>_base.scss</code> only provides code section background style, <code>_syntax-highlighting.scss</code> provides highlight style.

Update <code>_syntax-highlighting.scss</code> could change the highlight style. The default highlight style file in this theme is <code>_syntax-highlighting-native.scss</code>

After update, make sure include your highlight style file in <code>css/main.scss</code>

``` css
@import
        "base",
        "layout",
        "_syntax-highlighting-native" // change to "_syntax-highlighting"
;
```

**Comment by dbarobin** [comment]
Sorry, I make a mistake. Thanks for your patient explanation. :+1:
