### ISSUE TITLE
Why custom feature Google Analytics didn't work?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#11]
I add `Google Analytics` by tutorial(See at: http://t.cn/RwR2q7P), But it didn't work. Because I could not see any data from this custom feature. How to fix it? Thanks.

Sincerely,
Robin

**Comment by yulijia** [comment]
I could not reproduce your bug. My code works well on my website.
Please contact Google Analytics help center.

**Comment by dbarobin** [comment]
Thanks.
