### ISSUE TITLE
How to make the category case sensitive?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#12]
Hi, there. I dig out a problem which troubles me.

Categories of my blog:

```
tree _posts/ | more
```

> _posts/
> ├── Linux
> │   ├── xxx.md
> │   └── xxx.md
> ├── MySQL
> │   ├── xxx.md
> │   └── xxx.md
> ├── Other
> │   ├── xxx.md
> │   └── xxx.md
> └── Python
>     ├── xxx.md
>     └── xxx.md
> 
> 4 directories, 121 files

But it displays in the page as follows:

![Categories of my blog](https://cloud.githubusercontent.com/assets/3949252/6523446/d7ee1a04-c42a-11e4-82e5-91ab31aba987.png)

I want to make the category of my blog case sensitive, like **Linux**, **MySQL**, **Other**, **Python** etc. How to make it? Thanks.

Sincerely,
Robin

**Comment by yulijia** [comment]
Hi, @dbarobin 
Most of your questions are not related to this theme. You need learn more about Jekyll, and I think [So simple theme](https://github.com/mmistakes/so-simple-theme/) is better than Freshman21 theme, change it(So simple theme) to my theme(Freshman21) is like degradation.  I am also a newbie of Jekyll and theme design, Freshman21 is my 2nd theme and the only thing I want to shown in this theme is simple code without JS and using all default parameter of Jekyll. Category with capitalize letter are not the default parameter.

Also, please **google** your question to find some answers before you open an issue. If you have any question about Jekyll or JS, please sent me a email without open new issues. 

[Here is the answer of this issue](http://stackoverflow.com/questions/19649009/titleize-jekyll-category)

**add** <code>| capitalize</code> for each variable <code>cat</code> , please see below:

``` html
./c_categories.md:10:<a href="#{{ cat[0] }}" title="{{ cat[0] }}" rel="{{ cat[1].size }}">{{ cat[0] | join: "/" | capitalize}}<span class="size"> {{ cat[1].size }}</span></a>
./c_categories.md:16:<li id="{{ cat[0] }}">{{ cat[0] | capitalize }}</li>
./d_archives.md:22:&raquo; <a href="{{ site.baseurl }}{{ post.url }}">{{ post.title | capitalize }}</a><br />
./_includes/Categories.html:4:  <li><a href="{{ site.baseurl }}/categories/#{{ cat[0] }}" title="{{ cat[0] }}" rel="{{ cat[1].size }}">{{ cat[0] | capitalize}} ({{ cat[1].size }})</a></li>
./index.html:17:      <a href="{{site.baseurl}}/categories/#{{ cat }}">{{ cat | capitalize}}</a>&nbsp;
./_layouts/post.html:11:    <a href="{{site.baseurl}}/categories/#{{ cat }}">{{ cat | capitalize }}</a>&nbsp;
```

**Comment by dbarobin** [comment]
Sorry for my stupid question. I'll try to figure out by myself from now on. Thanks!
