### ISSUE TITLE
Extra slash at Recent Posts links

### ISSUE THREAD

**Issue by villasv** [yulijia/freshman21#15]
```
<div class="sidebar-module">
  <h4>{{ site.locales[site.default_locale].Recent_Posts }}</h4>
  {% for post in site.posts limit:5 %}
  <li>
  <a href="{{ site.baseurl }}/{{ post.url }}" title="{{ post.title }}" rel="bookmark">{{ post.title }}</a>
  </li>
  {% endfor %}
</div>
```

In the snippet above (`Recent_Posts.html`) the `{{ post.url }}` already comes with a prepending slash, so the compound `"{{ site.baseurl }}/{{ post.url }}`` gets one extra slash between the baseurl and the post url.

If the baseurl is not empty, the URL still works. If the baseurl is empty, the url won't be interpreted as relative path and the link will be broken.

**Comment by yulijia** [comment]
Hi, Victor
Thanks for your kind help. I remove extra slash at Recent_Posts.html and will check if there is any broken link when `baseurl` is empty.
