### ISSUE TITLE
typo in tags.md

### ISSUE THREAD

**Issue by imrickysu** [yulijia/freshman21#2]
`permalink: /tags/` in tags.md is mistyped to `premalink: /tags/`.
It causes jekyll generates _site/tags.html if _config.yml sets `permalink` to some style other than `pretty`.
After correcting it, /tags/ will be generated in stead of /tags.html, which is expected and the same style as categories.md.

**Comment by yulijia** [comment]
Hi, @imrickysu 
Thanks for you help, I fix this typo.
btw: Happy Chinese New Year!

**Comment by imrickysu** [comment]
Great. Happy Chinese New Year:)
