### ISSUE TITLE
Error deploying this theme

### ISSUE THREAD

**Issue by ghost** [yulijia/freshman21#25]
```
xx@kami:~/freshman21$ jekyll build --destination /var/www
Configuration file: /home/xx/blog/_config.yml
            Source: /home/xx/freshman21
       Destination: /var/www/
 Incremental build: disabled. Enable with --incremental
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Invalid US-ASCII character "\xE3" on line 324
jekyll 3.4.0 | Error:  Invalid US-ASCII character "\xE3" on line 324
```

**Comment by yulijia** [comment]
Hi, I think the problem may caused by a quotation mark. 
Please see here, [Error: invalid CP949 character](http://yulijia.net/freshman21/articles/2015/06/03/invalid-CP949-character.html)

you can try add a line at top of the  'css/main.scss'  file 

```
@charset "utf-8"
```

**Comment by Hitogami** [comment]
@yulijia  thanks that worked but now the site looks weird
[http://imgur.com/qmeQZnD](url)

**Comment by yulijia** [comment]
Hi @Hitogami 
Sorry for the delay in replying, do you fix the bug or not? 
If you couldn't fix it, please let me know.

**Comment by ghost** [comment]
@yulijia Yea fixed it thanks for trying to help me regardless 👍
