### ISSUE TITLE
Change `site.url` to `site.baseurl` can make it work at localhost

### ISSUE THREAD

**Issue by imrickysu** [yulijia/freshman21#3]
Ap categories.md and tags.md, creating post links with {{site.url}} always direct the link to external website.
In the situation that user would like to preview posts at localhost, change {{site.url}} to {{site.baseurl}} helps to make the theme work at both localhost and remote server.

**Comment by yulijia** [comment]
Thanks a lot.
I fix all site url bugs, now user can preview site at localhost with correct links.

**Comment by yulijia** [comment]
a great [article](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/) about <code>site.url</code> and <code>site.baseurl</code>.

**TL;DR: Use baseurl when you are building a site that doesn’t sit at the root of the domain.**
