### ISSUE TITLE
File to import not found or unreadable: base. on line 53

### ISSUE THREAD

**Issue by phlinhng** [yulijia/freshman21#34]
Hi, I am new to jekyll and really enjoying your theme. But I've face some problem when trying to ```jekyll serve``` the template on localhost and the following message showed.

> Conversion error: Jekyll::Converters::Scss encountered an error while converting 'blog/css/main.scss':
>                     File to import not found or unreadable: base. on line 53
> jekyll 3.8.5 | Error:  File to import not found or unreadable: base. on line 53

Do you have any idea how to fix it?

**Comment by yulijia** [comment]
Hi, @phlinhng Could you mind provide more information to help me to reproduce your problem? I use the same version of Jekyll as yours, however, I failed to reproduce your problem on my local computer.

**Comment by phlinhng** [comment]
I seemed to fix the problem myself after installing ```jekyll-paginate```. Thank you for replying!

**Comment by yulijia** [comment]
No problem.
