### ISSUE TITLE
Typo of recent.

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#4]
Thanks for you excellent work.

I discovered a typo. When we express some post which published lately, we use `recent posts`, not resent. 

All typo of resent are follows:

```
grep -rn Resent ./*
```

> ./_config.yml:33:      Resent_Posts: "Resent Posts"
> ./_config.yml:46:      Resent_Posts: "近期文章"
> ./_includes/Resent_Posts.html:2:  <h4>{{ site.locales[site.default_locale].Resent_Posts }}</h4>
> ./_includes/sidebar.html:4:{% include Resent_Posts.html %}
> ./_posts/2014-12-19-freshman21-structure.md:44:│   ├── Resent_Posts.html      # right column sidebar content
> ./_posts/2014-12-19-freshman21-structure.md:102:│   ├── Resent_Posts.html
> ./_posts/2014-12-19-how-to-set-the-config-file.md:77:  {\% include Resent_Posts.html \%}

I am looking forward to fix this typo. Thanks.

Sincerely,
Robin

**Comment by yulijia** [comment]
Hi, Robin 

Thank you.  I fixed the typo.
