### ISSUE TITLE
Why my custom javascript of backing to top don't work?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#5]
I used `So Simple Theme` before and I changed it to your theme yesterday. But I found a problem which worked well before. I added **Back to Top** feature by myself. The operations are follows:

**Step 1**, placed custom java script of backing to top feature. This java script can be shown at: http://git.io/xX5b

**Step 2**, added `scroll up image`, and this image can be obtained at: http://git.io/xXdk

**Step 3**, added custom div at `footer.html`, the code is follows:

``` js
<script src="/assets/js/vendor/jquery-1.9.1.min.js"></script>
<script src="/assets/js/totop.js"></script>
<footer class="site-footer">
   <div id="totop" style="position:fixed;bottom:150px;right:50px;cursor: pointer;">
      <a title="Back To Top"><img src="/images/scrollup.png"/></a>
   </div>
</footer>
```

After this three steps, the custom feature of backing to top finished. But it didn't work. It shown when I open any pages of my website, and when I click the scroll up image, nothing happened.

I am not familiar with java script, could you please help me? Thanks.

Sincerely,
Robin

**Comment by yulijia** [comment]
The **proper way** to include JavaScript in  **footer.html** file

``` html
<footer class="site-footer">
  <p> &copy; 2015 Robin Wen. All Rights Reserved.</p>
   <div id="totop" style="position:fixed;bottom:150px;right:50px;cursor: pointer;">
      <a title="Back To Top"><img src="/images/scrollup.png"/></a>
   </div>

<script src="/assets/js/vendor/jquery-1.9.1.min.js"></script>
<script src="/assets/js/totop.js"></script>  
</footer>

```

**Comment by dbarobin** [comment]
I fix this bug as you do. It appears I need to know more JavaScript. Thanks!
