### ISSUE TITLE
How to update font size of post content?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#6]
I tried to update font size of my website, and I updated this font size: title of site, link of post and title of post. But I am in a puzzle about `font size of post content`. Thanks.

Sincerely,
Robin

**Comment by yulijia** [comment]
I think you have already fixed it by yourself?

.post-content{
 font-size: 14px;
}

**Comment by dbarobin** [comment]
Yeah, I couldn't find the font-size attribute before, so I add this by myself. Thanks.
