### ISSUE TITLE
How to custom 404 page?

### ISSUE THREAD

**Issue by dbarobin** [yulijia/freshman21#9]
Adding 404 page to website is common sense, and this is useful for **user experience**. We are lucky that GitHub provides 404 page. But I want to custom 404 page, how to implement it? By the way, I tried to add custom 404 page by adding `404.md` file, but the title of this file(Page Not Found) was placed in the navigation automatically, this is so bad, so I remove it.

Thanks!

Sincerely,
Robin

**Comment by yulijia** [comment]
Please see Part 2 of  [this article](http://yulijia.net/freshman21/articles/howto/2014/12/19/freshman21-structure.html)

You need create a folder for each top-level page, then put 404.md at the root level of your GitHub Pages repository.

**Comment by dbarobin** [comment]
I'll try. Thanks.
